[package]
name = "todolist"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
eframe = "0.28.1"
egui = "0.28.1"
egui-modal = "0.4.0"
egui_extras = { version = "0.28.1", features = ["default", "all_loaders", "chrono"] }
